version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.4
    steps:
      - checkout
      - run:
          name: run the default task
          command: |
            gem install bundler -v 4.0.14
            bundle install
            bundle exec rake
